config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :abstracts, only: [:index]
  resources :journals
  resources :journal_feeds
  resources :keywords
  resources :subscriptions, except: [:index]
  resources :users, only: [:update] #this adds subscriptions to users
  resources :custom_keywords

  root 'subscriptions#index'

end

app/models/abstract.rb
class Abstract < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_body, :against => :body, :using => {
    :tsearch => {:prefix => true, :dictionary => "english"}
  }
    # :if => :user_is_subscribed_to_parent_journal?

  belongs_to :journal, dependent: :destroy
  has_many :keywords
  has_many :custom_keywords

  def has_keyword?(keyword)
    keywords.where(body: keyword.body).any?
  end

  def has_custom_keyword?(keyword)
    custom_keywords.where(body: keyword.body).any?
  end

  def user_is_subscribed_to_parent_journal?(current_user)
    journal.journal_feed.subscriptions.pluck(:user_id).include?(current_user.id)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custom_keyword.rb
class CustomKeyword < ApplicationRecord
  belongs_to :abstract, dependent: :destroy
  belongs_to :user

end

app/models/journal.rb
class Journal < ApplicationRecord
  has_many :abstracts
  belongs_to :journal_feed
end

app/models/journal_feed.rb
class JournalFeed < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  has_many :journals
  has_many :subscriptions
  has_many :users, through: :subscriptions

  def latest_journal
    journals.last
  end

  def sort_child_journals_by_date
    journals.sort_by { |journal| journal.date}.reverse
  end

  def all_abstracts_associated_with_journal_feed
    abstracts = []
    journals.each do |journal|
      journal.abstracts.each do |abstract|
        abstracts.push(abstract)
      end
    end
    abstracts.pluck(:body)
  end
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :abstract, dependent: :destroy

  def self.search(search)
    where("body ILIKE ?", "%#{search}%")
  end

  def self.subscribed_keywords(current_user)
    keywords = []
    current_user.subscriptions.each do |subscription|
      subscription.journal_feed.journals.each do |journal|
        journal.abstracts.each do |abstract|
          abstract.keywords.each {| keyword | keywords.push(keyword) }
        end
      end
    end
    keywords
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :journal_feed

  validates_presence_of :user
  validates_presence_of :journal_feed

  accepts_nested_attributes_for :journal_feed
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :subscriptions
  has_many :journal_feeds, through: :subscriptions
  has_many :custom_keywords
  
  accepts_nested_attributes_for :subscriptions
end

app/controllers/abstracts_controller.rb
class AbstractsController < ApplicationController

  def index

    if params[:search]
      @abstracts = Abstract.search_by_body(params[:search]).map {|abstract| abstract}
      @abstracts.uniq! {|abstract| abstract.body }
      @abstracts.uniq! {|abstract| abstract.title }
    else
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery prepend: true
  before_action :authenticate_user!

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  def index
    @journals = Journal.all
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def delete

  end

  def destroy
    #TODO admin only action
    Journal.find(params[:id]).destroy
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def show
    @keyword = Keyword.find(params[:id])
  end

  def index
    subscribed_keywords = Keyword.subscribed_keywords(current_user)
    keyword_count = Hash.new {[0, ""]}
    subscribed_keywords.each do |keyword| keyword_count[keyword.body] = [keyword_count[keyword.body][0]+=1,keyword]
    end
    @top_keywords = keyword_count.sort_by { |keyword, count| -count[0]}
    .first(10)

    if params[:search]
      all_keywords_matching_search = Keyword.search(params[:search]).order("body DESC")
      subscribed_keywords = []
      @keywords = all_keywords_matching_search.select do |keyword|
        keyword.abstract.user_is_subscribed_to_parent_journal?(current_user)
      end
      flash[:notice] = "No keywords found." if @keywords.empty?
    else
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    #this method updates subscriptions
    current_user.update(user_params)
    flash[:notice] = "Subscriptions updated!"
    redirect_to journal_feeds_path
  end

  private

  def user_params
    params.require(:user).permit(journal_feed_ids: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
end

app/helpers/abstracts_helper.rb
module AbstractsHelper





end

app/helpers/application_helper.rb
module ApplicationHelper

  def custom_keyword_belongs_to_current_user?(custom_keyword)
      custom_keyword.user_id == current_user.id
    end

    def format_abstract_body(abstract_body)
      strong_words = ["Conclusion:", "Results:", "Methods:", "Source:" ]
      results = []
      remove_extra_line_breaks(abstract_body).split(" ").each_with_index do |word, i|

        if substring_exists_in_array?(word, strong_words)
          results.push( "<br><br><strong>#{word}</strong>" )
        elsif i == 0
          results.push("<strong>Summary:</strong> #{word}")
        else
          results.push(word)
        end
      end
      results.join(" ")
    end

    def substring_exists_in_array?(substring, array)
      array.each do |ele|
        return true if ele.include?(substring) && substring.include?(":")
      end
      false
    end

    def remove_extra_line_breaks(abstract_body)
      #rss feeds include multiple breaks <br></br></br><br></br></br>
      #remove multiples for improved formatting

      results = abstract_body.split(" ").map do |ele|
        if (ele.include?("<br></br>") || ele.include?("</br><br>") || ele.include?("<br><br>")) && ele.length > 5
          new_ele = ele.gsub("<br>","").gsub("</br>","")
          "<br>" + new_ele + "<br>"

        else
          ele
        end
      end
      results.join(" ")
    end

    def randomized_background_image
    images = ["abstract1.jpg", "abstract0.jpg", "abstract2.jpg", "abstract3.jpg", "abstract4.jpg", "abstract5.jpg"]
    images[rand(images.size)]
    end

    def form_errors_for(object=nil)
      render('shared/form_errors', object: object) unless object.blank?
    end

end

app/helpers/custom_keywords_helper.rb
module CustomKeywordsHelper
end

app/helpers/journal_feeds_helper.rb
module JournalFeedsHelper
  def journal_title_and_date(journal_feed)
    journal_feed.title + " Latest issue: " + journal_feed.journals.last.date.to_s
  end

  def latest_journal_in_journal_feed(journal_feed)
    journal_feed.journals.sort_by()
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper

  def unique_and_sorted_keywords(keywords)
    keywords.uniq {|keyword| keyword.body} .sort_by { |keyword| keyword.body } 
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper

  def subscription_user_ids(journal_feed)
    subscription_ids = journal_feed.subscriptions.map {|subscription| subscription.user_id}
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abstracts/_form.html.erb
<div class="abstract-container">
  <br>
  <h4> <%= link_to abstract.title, abstract.url %> </h4>
  <br>
  <div> <strong>Authors:</strong>  <%= abstract.authors %></div>
  <br>
  <div> <%= format_abstract_body(abstract.body).html_safe %> </div>
  <br>
  <br>
</div>

app/views/abstracts/index.html.erb
<body class="vsc-initialized">
  <main role="main" class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-12 col-md-9 container">
        <div class="keyword-search-bar-container">
          <h3 class="keyword-search-header">Search all abstracts by keyword:</h3>
          <div class="keyword-search-bar">
            <%= form_tag(abstracts_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Keywords" %>
            <%= submit_tag "Search" %>
            <% end %>
          </div>
        </div>
        <% if @abstracts %>
            <ul class="keyword-list-group">
              <div class="search-results"><%= "showing #{@abstracts.length} results" %></div>
                <div class="abstracts-container">
                <% @abstracts.each do |abstract| %>
                <h3>Publication: <%= abstract.journal.title %></h3>
                  <li class="keyword-list-group-item">
                    <%= render partial: "abstracts/form", locals: {abstract: abstract} %>
                  </li>
                <% end %>
              </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/journals/index.html.erb
<!-- Journals index -->
<body class="vsc-initialized">
<main role="main" class="container">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-12 col-md-9">
      <h2>Abstracts</h2>
      <% @journals.each do |journal| %>
        <br>
        <% if journal.subscribed %>
          <% journal.abstracts.each do |abstract| %>
            <br>
            <h4> <%= link_to "#{abstract.title}", abstract.url %> </h4>
            <br>
            <div> <strong>Authors:</strong>  <%= abstract.authors %></div>
            <br>
            <div> <%= format_abstract_body(abstract.body).html_safe %> </div>
            <br>
            <ul class="keyword-list">
             <strong>Keywords:</strong>
              <% abstract.keywords.each do |keyword| %>
              <li class="keyword-list-item"> <%= keyword.body %> </li>
            <% end %>
            <br>
          <% end %>
        </ul>
        <br>
      <% end %>
    </div>
  <div class="col-6 col-md-3 sidebar-offcanvas" id="sidebar">
    <div class="">
      <h2>Available Journals</h2>
    </div>
    <% @journals.each do |journal| %>
        <%= journal.title %>
        <br>
        <%= form_for journal do |f| %>
          <%= f.label :subscribed %>
          <%= f.check_box :subscribed %>
          <%= f.submit "Update", class: "btn btn-success" %>
        <% end  %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>
</body>

app/views/keywords/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <h2 class="keywords-title">Search your subscribed journals for a keyword</h2>
      <div class="keyword-search-display">
        <% if @keywords %>
          <% unique_and_sorted_keywords(@keywords).each do |keyword| %>
            <span class="badge badge-primary"><%= link_to keyword.body, keyword_path(keyword.id), class: "keyword-text" %></span>
          <% end %>
        <% end %>
      </div>
      <div class="keyword-search-bar">
        <%= form_tag(keywords_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Keywords" %>
        <%= submit_tag "Search" %>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <div class="top-keywords-box">
        <h2>Top Keywords:</h2>
        <ul class="keyword-list">
          <% @top_keywords.each do |top_keyword_body, count_and_object| %>
            <li class="keyword-list-item-vertical">
              <button type="button" class="btn btn-primary">
                <%= link_to top_keyword_body, keyword_path(count_and_object[1].id), class: "keyword-text" %>
                <span class="badge badge-light"> <%= count_and_object[0] %> </span>
              </button>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/keywords/show.html.erb
<body class="vsc-initialized">
  <main role="main" class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-12 col-md-9">
        <h5>Now viewing abstracts associated with the <strong><%= @keyword.body %></strong> keyword</h5>
        <% @abstracts.each do |abstract| %>
          <% if abstract.has_keyword?(@keyword) && abstract.user_is_subscribed_to_parent_journal?(current_user) %>
            <br>
            <h4> <%= link_to abstract.title, abstract.url %> </h4>
            <br>
            <div> <strong>Authors:</strong>  <%= abstract.authors %></div>
            <br>
            <div> <%= abstract.body.html_safe %> </div>
            <br>
            <ul class="keyword-list">
             <strong>Keywords:</strong>
              <% abstract.keywords.each do |keyword| %>
              <li class="keyword-list-item"> <%= link_to keyword.body, keyword_path(keyword.id) %></li>
            <% end %>
            <br>
          <% end %>
        <% end  %>
      </div>
    </div>
  </div>
</body>