config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :abstracts, only: [:index]
  resources :journals
  resources :journal_feeds
  resources :keywords
  resources :subscriptions, except: [:index]
  resources :users, only: [:update] #this adds subscriptions to users
  resources :custom_keywords

  root 'subscriptions#index'

end

app/models/journal_feed.rb
class JournalFeed < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  has_many :journals
  has_many :subscriptions
  has_many :users, through: :subscriptions

  def latest_journal
    journals.last
  end

  def sort_child_journals_by_date
    journals.sort_by { |journal| journal.date}.reverse
  end

  def all_abstracts_associated_with_journal_feed
    abstracts = []
    journals.each do |journal|
      journal.abstracts.each do |abstract|
        abstracts.push(abstract)
      end
    end
    abstracts.pluck(:body)
  end
end

app/controllers/journal_feeds_controller.rb
class JournalFeedsController < ApplicationController
  require 'scraper'

  def show
    @journal_feed = JournalFeed.find(params[:id])
  end

  def index
    #Journal Feeds view only displays subscribed feeds.
    @journal_feeds = JournalFeed.joins(:subscriptions)
    .where('subscriptions.user_id' => current_user.id)
    .includes({:journals => :abstracts})
    .sort_by {|feed| feed.latest_journal.date}.reverse
    @custom_keyword = CustomKeyword.new
  end

  def new
    @journal_feed = JournalFeed.new
  end

  def create
    @journal_feed = JournalFeed.new(journal_feed_params)
    if journal_feed_url_is_valid?
      @journal_feed.save
      redirect_to @journal_feed
    else
      render 'subscriptions/index'
    end

  end

  def edit

  end

  def update

  end

  def delete
    @journal_feed = JournalFeed.find(params[:id])
    @journal_feed.destroy if @journal_feed.journals.empty?
  end

  private

  def journal_feed_params
    params.require(:journal_feed).permit(:title, :url)
  end

  def journal_feed_url_is_valid?
    #TODO check if this can be replaced by a custom validation at model level
    begin
      Feedjira::Feed.fetch_and_parse(@journal_feed.url)
      Scraper.new(@journal_feed)
      if !@journal_feed.journals.all.empty?
        return true
       else
        flash.now[:alert] = 'Abstractedly thinks the abstracts in this feed are too short to save, so it did not.'
        false
      end
    rescue
      flash.now[:alert] = "Abstractedly could not access this RSS feed. Check your URL and try again."
      false
    end
  end

end

app/helpers/journal_feeds_helper.rb
module JournalFeedsHelper
  def journal_title_and_date(journal_feed)
    journal_feed.title + " Latest issue: " + journal_feed.journals.last.date.to_s
  end

  def latest_journal_in_journal_feed(journal_feed)
    journal_feed.journals.sort_by()
  end
end

app/views/journal_feeds/index.html.erb
<html>
<head></head>
<body class="vsc-initialized">
  <main role="main" class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-12 col-md-9 container">
          <% @journal_feeds.each do |journal_feed| %>
              <%= content_tag(:div, journal_title_and_date(journal_feed), class: "card", type: "button", data: {toggle: "collapse", target: "#" + journal_title_and_date(journal_feed).gsub(" ", "")}) do %>
                <div class="card-body">
                   <h5 class="card-title"> <%= journal_feed.title %> </h5>
                   <h6 class="card-subtitle mb-2 text-muted">Last updated: <%= journal_feed.latest_journal.date %></h6>
                   <p class="card-text"></p>
                 </div>
              <% end %>
              <%= content_tag(:div, class: "journal-container collapse", id: journal_title_and_date(journal_feed).gsub(" ", "")) do %>
              <%= link_to "See all journal issues for #{journal_feed.title}", journal_feed_path(journal_feed), class: "journal-title" %>
              <h2 class="journal-date">Issue: <%= journal_feed.latest_journal.date %></h2>
              <% journal_feed.latest_journal.abstracts.each do |abstract| %>
                <%= render partial: "abstracts/form", locals: { abstract: abstract } %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</body>

app/views/journal_feeds/new.html.erb
<%= form_for @journal_feed, url: {action: "create"} do |f| %>
  <%= form_errors_for @journal_feed %>
  <%= f.label "Journal Title" %>
  <%= f.text_field :title %>
  <%= f.label "RSS Feed URL" %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/journal_feeds/show.html.erb
<html>
<head></head>
<body class="vsc-initialized">
  <main role="main" class="container">
    <div class="row row-offcanvas row-offcanvas-right">
      <div class="col-12 col-md-9 container">
          <% @journal_feed.sort_child_journals_by_date.each do |journal| %>
              <h2> <%= journal.title %> </h2>
              <h2 class="journal-date">Issue: <%= journal.date %></h2>
              <% journal.abstracts.each do |abstract| %>
                <%= render partial: "abstracts/form", locals: { abstract: abstract } %>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </main>
</body>